### ISSUE TITLE
Better way to get specific version of secret

### ISSUE THREAD

**Issue by jainhitesh9998** [quarkiverse/quarkus-vault#133]
I have integrated vault with appauth and kv - version 2 in my quarkus application.

when i wanted to load a specific version of secret, i have added it as query parameter in secret-config-kv-path, can it be decoupled from the path as another variable or since `secret-config-kv-path` takes list of paths, this is the way to go?

```
quarkus:
  vault:
    url: http://localhost:8200
    authentication:
      app-role:
        role-id: role-id
        secret-id: secret-id
    secret-config-kv-path: test/frac?version=2
    kv-secret-engine-mount-path: secret
```
